/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type BodyAuthCookieLoginApiAuthLoginPostGrantType = string | null;

export type BodyAuthCookieLoginApiAuthLoginPostClientId = string | null;

export type BodyAuthCookieLoginApiAuthLoginPostClientSecret = string | null;

export interface BodyAuthCookieLoginApiAuthLoginPost {
  grant_type?: BodyAuthCookieLoginApiAuthLoginPostGrantType;
  username: string;
  password: string;
  scope?: string;
  client_id?: BodyAuthCookieLoginApiAuthLoginPostClientId;
  client_secret?: BodyAuthCookieLoginApiAuthLoginPostClientSecret;
}

export interface BodyResetForgotPasswordApiAuthForgotPasswordPost {
  email: string;
}

export interface BodyResetResetPasswordApiAuthResetPasswordPost {
  token: string;
  password: string;
}

export interface BodyVerifyVerifyApiAuthVerifyPost {
  token: string;
}

export type ErrorModelDetailAnyOf = {[key: string]: string};

export type ErrorModelDetail = string | ErrorModelDetailAnyOf;

export interface ErrorModel {
  detail: ErrorModelDetail;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface OAuth2AuthorizeResponse {
  authorization_url: string;
}

export interface UserBeforeVerify {
  id: number;
  email: string;
  is_active?: boolean;
  is_superuser?: boolean;
  is_verified?: boolean;
}

export type UserCreateIsActive = boolean | null;

export type UserCreateIsSuperuser = boolean | null;

export type UserCreateIsVerified = boolean | null;

export interface UserCreate {
  email: string;
  password: string;
  is_active?: UserCreateIsActive;
  is_superuser?: UserCreateIsSuperuser;
  is_verified?: UserCreateIsVerified;
}

export interface UserRead {
  id: number;
  email: string;
  is_active?: boolean;
  is_superuser?: boolean;
  is_verified?: boolean;
}

export type UserUpdatePassword = string | null;

export type UserUpdateEmail = string | null;

export type UserUpdateIsActive = boolean | null;

export type UserUpdateIsSuperuser = boolean | null;

export type UserUpdateIsVerified = boolean | null;

export interface UserUpdate {
  password?: UserUpdatePassword;
  email?: UserUpdateEmail;
  is_active?: UserUpdateIsActive;
  is_superuser?: UserUpdateIsSuperuser;
  is_verified?: UserUpdateIsVerified;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type OauthGoogleCookieAuthorizeApiAuthGoogleAuthorizeGetParams = {
scopes?: string[];
};

export type OauthGoogleCookieCallbackApiAuthGoogleCallbackGetParams = {
code?: string | null;
code_verifier?: string | null;
state?: string | null;
error?: string | null;
};

export const getFastAPI = () => {
/**
 * @summary Auth:Cookie.Login
 */
const authCookieLoginApiAuthLoginPost = <TData = AxiosResponse<unknown | void>>(
    bodyAuthCookieLoginApiAuthLoginPost: BodyAuthCookieLoginApiAuthLoginPost, options?: AxiosRequestConfig
 ): Promise<TData> => {const formUrlEncoded = new URLSearchParams();
if(bodyAuthCookieLoginApiAuthLoginPost.grant_type !== undefined && bodyAuthCookieLoginApiAuthLoginPost.grant_type !== null) {
 formUrlEncoded.append(`grant_type`, bodyAuthCookieLoginApiAuthLoginPost.grant_type)
 }
formUrlEncoded.append(`username`, bodyAuthCookieLoginApiAuthLoginPost.username)
formUrlEncoded.append(`password`, bodyAuthCookieLoginApiAuthLoginPost.password)
if(bodyAuthCookieLoginApiAuthLoginPost.scope !== undefined) {
 formUrlEncoded.append(`scope`, bodyAuthCookieLoginApiAuthLoginPost.scope)
 }
if(bodyAuthCookieLoginApiAuthLoginPost.client_id !== undefined && bodyAuthCookieLoginApiAuthLoginPost.client_id !== null) {
 formUrlEncoded.append(`client_id`, bodyAuthCookieLoginApiAuthLoginPost.client_id)
 }
if(bodyAuthCookieLoginApiAuthLoginPost.client_secret !== undefined && bodyAuthCookieLoginApiAuthLoginPost.client_secret !== null) {
 formUrlEncoded.append(`client_secret`, bodyAuthCookieLoginApiAuthLoginPost.client_secret)
 }

    return axios.default.post(
      `/api/auth/login`,
      formUrlEncoded,options
    );
  }

/**
 * @summary Auth:Cookie.Logout
 */
const authCookieLogoutApiAuthLogoutPost = <TData = AxiosResponse<unknown | void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/logout`,undefined,options
    );
  }

/**
 * Не регирируем пользователя сразу,
создаем данные для регистрации и валидируем их
 * @summary Register:Register
 */
const registerRegisterApiAuthRegisterPost = <TData = AxiosResponse<void>>(
    userCreate: UserCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/register`,
      userCreate,options
    );
  }

/**
 * @summary Reset:Forgot Password
 */
const resetForgotPasswordApiAuthForgotPasswordPost = <TData = AxiosResponse<unknown>>(
    bodyResetForgotPasswordApiAuthForgotPasswordPost: BodyResetForgotPasswordApiAuthForgotPasswordPost, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/forgot-password`,
      bodyResetForgotPasswordApiAuthForgotPasswordPost,options
    );
  }

/**
 * @summary Reset:Reset Password
 */
const resetResetPasswordApiAuthResetPasswordPost = <TData = AxiosResponse<unknown>>(
    bodyResetResetPasswordApiAuthResetPasswordPost: BodyResetResetPasswordApiAuthResetPasswordPost, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/reset-password`,
      bodyResetResetPasswordApiAuthResetPasswordPost,options
    );
  }

/**
 * @summary Verify:Verify
 */
const verifyVerifyApiAuthVerifyPost = <TData = AxiosResponse<UserBeforeVerify>>(
    bodyVerifyVerifyApiAuthVerifyPost: BodyVerifyVerifyApiAuthVerifyPost, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/verify`,
      bodyVerifyVerifyApiAuthVerifyPost,options
    );
  }

/**
 * @summary Oauth:Google.Cookie.Authorize
 */
const oauthGoogleCookieAuthorizeApiAuthGoogleAuthorizeGet = <TData = AxiosResponse<OAuth2AuthorizeResponse>>(
    params?: OauthGoogleCookieAuthorizeApiAuthGoogleAuthorizeGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/auth/google/authorize`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * The response varies based on the authentication backend used.
 * @summary Oauth:Google.Cookie.Callback
 */
const oauthGoogleCookieCallbackApiAuthGoogleCallbackGet = <TData = AxiosResponse<unknown>>(
    params?: OauthGoogleCookieCallbackApiAuthGoogleCallbackGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/auth/google/callback`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Users:Current User
 */
const usersCurrentUserApiUsersMeGet = <TData = AxiosResponse<UserRead>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/users/me`,options
    );
  }

/**
 * @summary Users:Patch Current User
 */
const usersPatchCurrentUserApiUsersMePatch = <TData = AxiosResponse<UserRead>>(
    userUpdate: UserUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.patch(
      `/api/users/me`,
      userUpdate,options
    );
  }

/**
 * @summary Users:User
 */
const usersUserApiUsersIdGet = <TData = AxiosResponse<UserRead>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/users/${id}`,options
    );
  }

/**
 * @summary Users:Patch User
 */
const usersPatchUserApiUsersIdPatch = <TData = AxiosResponse<UserRead>>(
    id: string,
    userUpdate: UserUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.patch(
      `/api/users/${id}`,
      userUpdate,options
    );
  }

/**
 * @summary Users:Delete User
 */
const usersDeleteUserApiUsersIdDelete = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/users/${id}`,options
    );
  }

/**
 * @summary Token:Refresh Token
 */
const tokenRefreshTokenApiAuthRefreshPost = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/refresh`,undefined,options
    );
  }

return {authCookieLoginApiAuthLoginPost,authCookieLogoutApiAuthLogoutPost,registerRegisterApiAuthRegisterPost,resetForgotPasswordApiAuthForgotPasswordPost,resetResetPasswordApiAuthResetPasswordPost,verifyVerifyApiAuthVerifyPost,oauthGoogleCookieAuthorizeApiAuthGoogleAuthorizeGet,oauthGoogleCookieCallbackApiAuthGoogleCallbackGet,usersCurrentUserApiUsersMeGet,usersPatchCurrentUserApiUsersMePatch,usersUserApiUsersIdGet,usersPatchUserApiUsersIdPatch,usersDeleteUserApiUsersIdDelete,tokenRefreshTokenApiAuthRefreshPost}};
export type AuthCookieLoginApiAuthLoginPostResult = AxiosResponse<unknown | void>
export type AuthCookieLogoutApiAuthLogoutPostResult = AxiosResponse<unknown | void>
export type RegisterRegisterApiAuthRegisterPostResult = AxiosResponse<void>
export type ResetForgotPasswordApiAuthForgotPasswordPostResult = AxiosResponse<unknown>
export type ResetResetPasswordApiAuthResetPasswordPostResult = AxiosResponse<unknown>
export type VerifyVerifyApiAuthVerifyPostResult = AxiosResponse<UserBeforeVerify>
export type OauthGoogleCookieAuthorizeApiAuthGoogleAuthorizeGetResult = AxiosResponse<OAuth2AuthorizeResponse>
export type OauthGoogleCookieCallbackApiAuthGoogleCallbackGetResult = AxiosResponse<unknown>
export type UsersCurrentUserApiUsersMeGetResult = AxiosResponse<UserRead>
export type UsersPatchCurrentUserApiUsersMePatchResult = AxiosResponse<UserRead>
export type UsersUserApiUsersIdGetResult = AxiosResponse<UserRead>
export type UsersPatchUserApiUsersIdPatchResult = AxiosResponse<UserRead>
export type UsersDeleteUserApiUsersIdDeleteResult = AxiosResponse<void>
export type TokenRefreshTokenApiAuthRefreshPostResult = AxiosResponse<void>
