/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface BodyAuthCookieLoginApiAuthLoginPost {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
}

export interface BodyVerifyVerifyApiAuthVerifyPost {
  token: string;
}

export interface EmailForgotPass {
  email: string;
}

export type ErrorModelDetail = string | {[key: string]: string};

export interface ErrorModel {
  detail: ErrorModelDetail;
}

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface ResetPass {
  password: string;
  token: string;
}

export interface StatusResponse {
  status: string;
}

export interface UserBeforeVerify {
  /**
     * @maximum 2147483647
     * @exclusiveMinimum 0
     */
  id: number;
  email: string;
  is_active?: boolean;
  is_superuser?: boolean;
  is_verified?: boolean;
}

export interface UserCreate {
  email: string;
  password: string;
  is_active?: boolean | null;
  is_superuser?: boolean;
  is_verified?: boolean | null;
}

export interface UserRead {
  /**
     * @maximum 2147483647
     * @exclusiveMinimum 0
     */
  id: number;
  email: string;
  is_active?: boolean;
  is_superuser?: boolean;
  is_verified?: boolean;
}

export interface UserUpdateEmail {
  current_email: string;
  new_email: string;
  password: string;
}

export interface UserUpdatePassword {
  current_password: string;
  new_password: string;
}

export const getFastAPI = (axiosInstance: AxiosInstance = axios.default) => {
/**
 * @summary Auth:Cookie.Login
 */
const authCookieLoginApiAuthLoginPost = (
    bodyAuthCookieLoginApiAuthLoginPost: BodyAuthCookieLoginApiAuthLoginPost, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown | void>> => {const formUrlEncoded = new URLSearchParams();
if(bodyAuthCookieLoginApiAuthLoginPost.grant_type !== undefined && bodyAuthCookieLoginApiAuthLoginPost.grant_type !== null) {
 formUrlEncoded.append(`grant_type`, bodyAuthCookieLoginApiAuthLoginPost.grant_type);
 }
formUrlEncoded.append(`username`, bodyAuthCookieLoginApiAuthLoginPost.username);
formUrlEncoded.append(`password`, bodyAuthCookieLoginApiAuthLoginPost.password);
if(bodyAuthCookieLoginApiAuthLoginPost.scope !== undefined) {
 formUrlEncoded.append(`scope`, bodyAuthCookieLoginApiAuthLoginPost.scope);
 }
if(bodyAuthCookieLoginApiAuthLoginPost.client_id !== undefined && bodyAuthCookieLoginApiAuthLoginPost.client_id !== null) {
 formUrlEncoded.append(`client_id`, bodyAuthCookieLoginApiAuthLoginPost.client_id);
 }
if(bodyAuthCookieLoginApiAuthLoginPost.client_secret !== undefined && bodyAuthCookieLoginApiAuthLoginPost.client_secret !== null) {
 formUrlEncoded.append(`client_secret`, bodyAuthCookieLoginApiAuthLoginPost.client_secret);
 }

    return axiosInstance.post(
      `/api/auth/login`,
      formUrlEncoded,options
    );
  }
const getAuthCookieLoginApiAuthLoginPostUrl = () => {

  return axiosInstance.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/auth/login`,
    baseURL: '',


  });
}

/**
 * @summary Auth:Cookie.Logout
 */
const authCookieLogoutApiAuthLogoutPost = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown | void>> => {
    return axiosInstance.post(
      `/api/auth/logout`,
      undefined,options
    );
  }
const getAuthCookieLogoutApiAuthLogoutPostUrl = () => {

  return axiosInstance.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/auth/logout`,
    baseURL: '',


  });
}

/**
 * Не регирируем пользователя сразу,
 * создаем данные для регистрации и валидируем их
 * @summary Register:Register
 */
const registerRegisterApiAuthRegisterPost = (
    userCreate: UserCreate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/auth/register`,
      userCreate,options
    );
  }
const getRegisterRegisterApiAuthRegisterPostUrl = () => {

  return axiosInstance.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/auth/register`,
    baseURL: '',


  });
}

/**
 * @summary Reset:Forgot Password
 */
const resetForgotPasswordApiAuthForgotPasswordPost = (
    emailForgotPass: EmailForgotPass, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.post(
      `/api/auth/forgot-password`,
      emailForgotPass,options
    );
  }
const getResetForgotPasswordApiAuthForgotPasswordPostUrl = () => {

  return axiosInstance.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/auth/forgot-password`,
    baseURL: '',


  });
}

/**
 * @summary Reset:Reset Password
 */
const resetResetPasswordApiAuthResetPasswordPost = (
    resetPass: ResetPass, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.post(
      `/api/auth/reset-password`,
      resetPass,options
    );
  }
const getResetResetPasswordApiAuthResetPasswordPostUrl = () => {

  return axiosInstance.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/auth/reset-password`,
    baseURL: '',


  });
}

/**
 * @summary Verify:Verify
 */
const verifyVerifyApiAuthVerifyPost = (
    bodyVerifyVerifyApiAuthVerifyPost: BodyVerifyVerifyApiAuthVerifyPost, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserBeforeVerify>> => {
    return axiosInstance.post(
      `/api/auth/verify`,
      bodyVerifyVerifyApiAuthVerifyPost,options
    );
  }
const getVerifyVerifyApiAuthVerifyPostUrl = () => {

  return axiosInstance.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/auth/verify`,
    baseURL: '',


  });
}

/**
 * @summary Users:Current User
 */
const usersCurrentUserApiUsersMeGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserRead>> => {
    return axiosInstance.get(
      `/api/users/me`,options
    );
  }
const getUsersCurrentUserApiUsersMeGetUrl = () => {

  return axiosInstance.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/users/me`,
    baseURL: '',


  });
}

/**
 * @summary Users:Patch Pass Current User
 */
const usersPatchPassCurrentUserApiUsersMeChangePasswordPost = (
    userUpdatePassword: UserUpdatePassword, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StatusResponse>> => {
    return axiosInstance.post(
      `/api/users/me/change-password`,
      userUpdatePassword,options
    );
  }
const getUsersPatchPassCurrentUserApiUsersMeChangePasswordPostUrl = () => {

  return axiosInstance.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/users/me/change-password`,
    baseURL: '',


  });
}

/**
 * @summary Users:Patch Email Current User
 */
const usersPatchEmailCurrentUserApiUsersMeRequestChangeEmailPost = (
    userUpdateEmail: UserUpdateEmail, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StatusResponse>> => {
    return axiosInstance.post(
      `/api/users/me/request-change-email`,
      userUpdateEmail,options
    );
  }
const getUsersPatchEmailCurrentUserApiUsersMeRequestChangeEmailPostUrl = () => {

  return axiosInstance.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/users/me/request-change-email`,
    baseURL: '',


  });
}

/**
 * @summary Token:Refresh Token
 */
const tokenRefreshTokenApiAuthRefreshPost = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/auth/refresh`,
      undefined,options
    );
  }
const getTokenRefreshTokenApiAuthRefreshPostUrl = () => {

  return axiosInstance.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/api/auth/refresh`,
    baseURL: '',


  });
}

/**
 * @summary Health Check
 */
const healthCheckAuthHealthGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.get(
      `/auth/health`,options
    );
  }
const getHealthCheckAuthHealthGetUrl = () => {

  return axiosInstance.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/auth/health`,
    baseURL: '',


  });
}

return {authCookieLoginApiAuthLoginPost,authCookieLogoutApiAuthLogoutPost,registerRegisterApiAuthRegisterPost,resetForgotPasswordApiAuthForgotPasswordPost,resetResetPasswordApiAuthResetPasswordPost,verifyVerifyApiAuthVerifyPost,usersCurrentUserApiUsersMeGet,usersPatchPassCurrentUserApiUsersMeChangePasswordPost,usersPatchEmailCurrentUserApiUsersMeRequestChangeEmailPost,tokenRefreshTokenApiAuthRefreshPost,healthCheckAuthHealthGet,getAuthCookieLoginApiAuthLoginPostUrl,getAuthCookieLogoutApiAuthLogoutPostUrl,getRegisterRegisterApiAuthRegisterPostUrl,getResetForgotPasswordApiAuthForgotPasswordPostUrl,getResetResetPasswordApiAuthResetPasswordPostUrl,getVerifyVerifyApiAuthVerifyPostUrl,getUsersCurrentUserApiUsersMeGetUrl,getUsersPatchPassCurrentUserApiUsersMeChangePasswordPostUrl,getUsersPatchEmailCurrentUserApiUsersMeRequestChangeEmailPostUrl,getTokenRefreshTokenApiAuthRefreshPostUrl,getHealthCheckAuthHealthGetUrl}};
export type AuthCookieLoginApiAuthLoginPostResult = AxiosResponse<unknown | void>
export type AuthCookieLogoutApiAuthLogoutPostResult = AxiosResponse<unknown | void>
export type RegisterRegisterApiAuthRegisterPostResult = AxiosResponse<void>
export type ResetForgotPasswordApiAuthForgotPasswordPostResult = AxiosResponse<unknown>
export type ResetResetPasswordApiAuthResetPasswordPostResult = AxiosResponse<unknown>
export type VerifyVerifyApiAuthVerifyPostResult = AxiosResponse<UserBeforeVerify>
export type UsersCurrentUserApiUsersMeGetResult = AxiosResponse<UserRead>
export type UsersPatchPassCurrentUserApiUsersMeChangePasswordPostResult = AxiosResponse<StatusResponse>
export type UsersPatchEmailCurrentUserApiUsersMeRequestChangeEmailPostResult = AxiosResponse<StatusResponse>
export type TokenRefreshTokenApiAuthRefreshPostResult = AxiosResponse<void>
export type HealthCheckAuthHealthGetResult = AxiosResponse<unknown>
